kind: pipeline
type: docker
name: default

trigger:
  event:
    include:
    - push
    - pull_request
  branch:
    - main

steps:
- name: terraform-lint
  image: hashicorp/terraform:1.6
  commands:
    - "terraform fmt -diff -check -recursive"

- name: run-sanity-checks
  image: hashicorp/terraform:1.6
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_key
    AWS_DEFAULT_REGION: us-east-1
  commands:
    - "./scripts/run_sanity_checks.sh tests"
