variable "prefix" {
  default     = "rancher-terraform"
  description = "Prefix added to names of all resources"
  type        = string
}

variable "project_id" {
  default     = null
  description = "Google Cloud project ID"
  type        = string
}

variable "region" {
  default     = "us-west2"
  description = "Google Region to create the resources"
  type        = string

  validation {
    condition = contains([
      "asia-east1",
      "asia-east2",
      "asia-northeast1",
      "asia-northeast2",
      "asia-northeast3",
      "asia-south1",
      "asia-south2",
      "asia-southeast1",
      "asia-southeast2",
      "australia-southeast1",
      "australia-southeast2",
      "europe-central2",
      "europe-north1",
      "europe-southwest1",
      "europe-west1",
      "europe-west10",
      "europe-west12",
      "europe-west2",
      "europe-west3",
      "europe-west4",
      "europe-west6",
      "europe-west8",
      "europe-west9",
      "me-central1",
      "me-central2",
      "me-west1",
      "northamerica-northeast1",
      "northamerica-northeast2",
      "southamerica-east1",
      "southamerica-west1",
      "us-central1",
      "us-east1",
      "us-east4",
      "us-east5",
      "us-south1",
      "us-west1",
      "us-west2",
      "us-west3",
      "us-west4",
    ], var.region)
    error_message = "Invalid Region specified!"
  }
}

# variable "create_ssh_key_pair" {
#   description = "Specify if a new SSH key pair needs to be created for the instances"
#   default     = true
#}

variable "ssh_private_key_path" {
  default     = null
  description = "The full path where is present the pre-generated SSH PRIVATE key (not generated by Terraform); if `create_ssh_key_pair = false` this variable must be set"
  type        = string
}

# variable "ssh_private_key_path" {}

# variable "ssh_public_key_path" {}

# variable "ip_cidr_range" {}

# variable "vpc" {}

# variable "subnet" {}

# variable "create_firewall" {}

variable "instance_count" {
  default     = null
  description = "Number of instances to be created"
  type        = number
}

# variable "instance_disk_size" {}

# variable "disk_type" {}

# variable "instance_type" {}

# variable "os_image" {}

variable "ssh_username" {
  default     = null
  description = "Username used for SSH with sudo access"
  type        = string
}

variable "startup_script" {
  default     = "export DEBIAN_FRONTEND=noninteractive ; curl -sSL https://releases.rancher.com/install-docker/20.10.sh | sh - ; sudo usermod -aG docker ubuntu ; newgrp docker ; sudo sysctl -w net.bridge.bridge-nf-call-iptables=1 ; sleep 180"
  description = "Script that will run when the VMs start"
  type        = string
}

variable "waiting_time" {
  default     = 180
  description = "Waiting time (in seconds)"
  type        = string
}

# variable "kubernetes_version" {}

variable "ingress_provider" {
  default     = "nginx"
  description = "Ingress controller provider"
  type        = string
}

variable "bootstrap_rancher" {
  default     = true
  description = "Bootstrap the Rancher installation"
  type        = bool
}

variable "rancher_hostname" {
  default     = null
  description = "Hostname for Rancher server"
  type        = string
}

variable "rancher_password" {
  default     = null
  description = "Password for accessing Rancher server (minimum 12 characters)"
  type = string

  validation {
    condition     = length(var.rancher_password) >= 12
    error_message = "The password must be at least 12 characters."
  }
}

variable "rancher_version" {
  default     = null
  description = "Rancher version to install"
  type        = string
}
