variable "prefix" {
  description = "The prefix used in front of all Azure resources"
  type        = string
}

variable "tag_begin" {
  type        = string
  description = "tag number added to DigitalOcean droplet"
  default     = 1
}

variable "region" {
  description = "Specifies the Azure region used for all resources. Default is 'westeurope'."
  type        = string
  default     = "westeurope"
  validation {
    condition = contains([
      "australiacentral",
      "australiacentral2",
      "australiaeast",
      "australiasoutheast",
      "austriaeast",
      "brazilsouth",
      "brazilsoutheast",
      "canadacentral",
      "canadaeast",
      "centralindia",
      "centralus",
      "centraluseuap",
      "chilecentral",
      "eastasia",
      "eastus",
      "eastus2",
      "eastus2euap",
      "francecentral",
      "francesouth",
      "germanynorth",
      "germanywestcentral",
      "indonesiacentral",
      "israelcentral",
      "italynorth",
      "japaneast",
      "japanwest",
      "jioindiacentral",
      "jioindiawest",
      "koreacentral",
      "koreasouth",
      "malaysiasouth",
      "malaysiawest",
      "mexicocentral",
      "northcentralus",
      "northeurope",
      "norwayeast",
      "norwaywest",
      "polandcentral",
      "southafricanorth",
      "southafricawest",
      "southcentralus",
      "southcentralusstg",
      "southeastasia",
      "southindia",
      "spaincentral",
      "swedencentral",
      "switzerlandnorth",
      "switzerlandwest",
      "taiwannorth",
      "uaenorth",
      "uksouth",
      "ukwest",
      "westcentralus",
      "westeurope",
      "westus",
      "westus2",
      "westus3"
    ], var.region)
    error_message = "Invalid Region specified."
  }
}

variable "create_ssh_key_pair" {
  description = "Specify if a new SSH key pair needs to be created for the instances"
  type        = bool
  default     = true
}

variable "ssh_private_key_path" {
  description = "The full path where is present the pre-generated SSH PRIVATE key (not generated by Terraform)"
  type        = string
  default     = null
}

variable "ssh_public_key_path" {
  description = "The full path where is present the pre-generated SSH PUBLIC key (not generated by Terraform)"
  type        = string
  default     = null
}

variable resource_group_location {
  description = "Specify location of resource group"
  type        = string
  default     = null
}

variable resource_group_name {
  description = "Specify name of resource group"
  type        = string
  default     = null
}

variable "create_rg" {
  description = "Specify if resource group needs to be created"
  type        = bool
  default     = true
}

variable "ip_cidr_range" {
  description = "Range of private IPs available for the Azure Subnet"
  type        = string
  default     = "10.10.0.0/24"
}

variable "create_vnet" {
  description = "Specifies whether a Virtual Network should be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "create_subnet" {
  description = "Specifies whether a Virtual Subnet should be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "subnet_id" {
  description = "Azure subnet id from inside Azure vnet "
  type        = string
  default     = null
}

variable "create_firewall" {
  description = "Azure Network security rule used for all resources"
  type        = bool
  default     = true
}

variable "network_security_group_id" {
  description = "Azure Network Security group id required to attach NIC to "
  type        = string
  default     = null
}

variable "instance_count" {
  description = "The number of nodes"
  type        = number
  default     = 3
}

variable "instance_disk_size" {
  description = "Size of the disk attached to each node, specified in GB"
  type        = number
  default     = 50
}

variable "disk_type" {
  description = "Specifies the type of the disks attached to each node ('Standard_LRS, 'StandardSSD_LRS', 'Premium_LRS' or 'UltraSSD_LRS'). Default is 'Premium_LRS'."
  type        = string
  default     = "Standard_LRS"
}

variable "instance_type" {
  description = "The name of a Virtual Machine instance type"
  type        = string
  default     = "Standard_D2_v5"
}

variable "spot_instance" {
  description = "Specify if Spot instances feature is enabled on Azure Virtual Machines"
  type        = bool
  default     = true
}

variable "os_type" {
  description = "Operating system type (sles or ubuntu)"
  type        = string
  default     = "sles"

  validation {
    condition     = contains(["sles", "ubuntu"], var.os_type)
    error_message = "The operating system type must be 'sles' or 'ubuntu'."
  }
}

variable "startup_script" {
  description = "Custom startup script"
  type        = string
  default     = null
}
