variable "prefix" {
  description = "The prefix used in front of all Azure resources"
  type        = string
}

variable "tag_begin" {
  type        = string
  description = "tag number added to Azure Virtual Machines"
  default     = 2
}

variable "subscription_id" {
  description = "Specifies the Azure Subscription ID that will contain all created resources. Default is 'azure-tf'."
  type        = string
  default     = "azure-tf"
}

variable "region" {
  description = "Specifies the Azure region used for all resources. Default is 'westeurope'."
  type        = string
  default     = "westeurope"
  validation {
    condition = contains([
      "australiacentral",
      "australiacentral2",
      "australiaeast",
      "australiasoutheast",
      "austriaeast",
      "brazilsouth",
      "brazilsoutheast",
      "canadacentral",
      "canadaeast",
      "centralindia",
      "centralus",
      "centraluseuap",
      "chilecentral",
      "eastasia",
      "eastus",
      "eastus2",
      "eastus2euap",
      "francecentral",
      "francesouth",
      "germanynorth",
      "germanywestcentral",
      "indonesiacentral",
      "israelcentral",
      "italynorth",
      "japaneast",
      "japanwest",
      "jioindiacentral",
      "jioindiawest",
      "koreacentral",
      "koreasouth",
      "malaysiasouth",
      "malaysiawest",
      "mexicocentral",
      "northcentralus",
      "northeurope",
      "norwayeast",
      "norwaywest",
      "polandcentral",
      "southafricanorth",
      "southafricawest",
      "southcentralus",
      "southcentralusstg",
      "southeastasia",
      "southindia",
      "spaincentral",
      "swedencentral",
      "switzerlandnorth",
      "switzerlandwest",
      "taiwannorth",
      "uaenorth",
      "uksouth",
      "ukwest",
      "westcentralus",
      "westeurope",
      "westus",
      "westus2",
      "westus3"
    ], var.region)
    error_message = "Invalid Region specified."
  }
}

variable "create_ssh_key_pair" {
  description = "Specify if a new SSH key pair needs to be created for the instances"
  type        = bool
  default     = true
}

variable "ssh_private_key_path" {
  description = "The full path where is present the pre-generated SSH PRIVATE key (not generated by Terraform)"
  type        = string
  default     = null
}

variable "ssh_public_key_path" {
  description = "The full path where is present the pre-generated SSH PUBLIC key (not generated by Terraform)"
  type        = string
  default     = null
}

variable "create_rg" {
  description = "Specify if resource group needs to be created"
  type        = bool
  default     = true
}

variable "create_vnet" {
  description = "Specifies whether a Virtual Network should be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "create_subnet" {
  description = "Specifies whether a Virtual Subnet should be created for the instances. Default is 'true'."
  type        = bool
  default     = true
}

variable "create_firewall" {
  description = "Azure Network security rule used for all resources"
  type        = bool
  default     = true
}

variable "server_instance_count" {
  description = "The number of Server nodes"
  type        = number
  default     = 3

  validation {
    condition = contains([
      1,
      3,
      5,
    ], var.server_instance_count)
    error_message = "Invalid number of Server nodes specified! The value must be 1, 3 or 5 (ETCD quorum)."
  }
}

variable "worker_instance_count" {
  description = "The number of Worker nodes"
  type        = number
  default     = 1
}

variable "instance_disk_size" {
  description = "Size of the disk attached to each node, specified in GB"
  type        = number
  default     = 50
}

variable "disk_type" {
  description = "Specifies the type of the disks attached to each node ('Standard_LRS, 'StandardSSD_LRS', 'Premium_LRS' or 'UltraSSD_LRS'). Default is 'Premium_LRS'."
  type        = string
  default     = "Standard_LRS"
}

variable "instance_type" {
  description = "The name of a Virtual Machine instance type"
  type        = string
  default     = "Standard_D2_v5"
}

variable "spot_instance" {
  description = "Specify if Spot instances feature is enabled on Azure Virtual Machines"
  type        = bool
  default     = true
}

variable "os_type" {
  description = "Operating system type (sles or ubuntu)"
  type        = string
  default     = "sles"

  validation {
    condition     = contains(["sles", "ubuntu"], var.os_type)
    error_message = "The operating system type must be 'sles' or 'ubuntu'."
  }
}

variable "startup_script" {
  description = "Custom startup script"
  type        = string
  default     = null
}

variable "k3s_version" {
  description = "Kubernetes version to use for the K3s cluster"
  type        = string
  default     = "v1.28.9+k3s1" #Version compatible with Rancher v2.8.3
}

variable "k3s_channel" {
  description = "K3s channel to use, the latest patch version for the provided minor version will be used"
  type        = string
  default     = null
}

variable "k3s_token" {
  description = "Token to use when configuring K3s nodes"
  type        = string
  default     = null
}

variable "k3s_config" {
  description = "Additional K3s configuration to add to the config.yaml file"
  type        = string
  default     = null
}

variable "kube_config_path" {
  description = "The path to write the kubeconfig for the RKE cluster"
  type        = string
  default     = null
}

variable "kube_config_filename" {
  description = "Filename to write the kube config"
  type        = string
  default     = null
}

variable "bootstrap_rancher" {
  description = "Bootstrap the Rancher installation"
  type        = bool
  default     = true
}

variable "rancher_hostname" {
  description = "Hostname to set when installing Rancher"
  type        = string
  default     = "rancher"
}

variable "rancher_bootstrap_password" {
  description = "Password to use when bootstrapping Rancher (min 12 characters)"
  type        = string
  default     = "initial-bootstrap-password"

  validation {
    condition     = var.rancher_bootstrap_password == null ? true : length(var.rancher_bootstrap_password) >= 12
    error_message = "The password provided for Rancher (rancher_bootstrap_password) must be at least 12 characters"
  }
}

variable "rancher_password" {
  description = "Password for the Rancher admin account (min 12 characters)"
  type        = string
  default     = null

  validation {
    condition     = var.rancher_password == null ? true : length(var.rancher_password) >= 12
    error_message = "The password provided for Rancher (rancher_password) must be at least 12 characters"
  }
}

variable "rancher_version" {
  description = "Rancher version to install"
  type        = string
  default     = null
}

variable "rancher_ingress_class_name" {
  description = "Rancher ingressClassName value"
  type        = string
  default     = "traefik"
}

variable "rancher_service_type" {
  description = "Rancher serviceType value"
  type        = string
  default     = "ClusterIP"
}
