variable "prefix" {
  description = "The prefix used in front of all Google resources"
}

variable "project_id" {
  description = "The ID of the Google Project that will contain all created resources"
}

variable "region" {
  description = "Google Region to create the resources"
  default     = "us-west2"

  validation {
    condition = contains([
      "asia-east1",
      "asia-east2",
      "asia-northeast1",
      "asia-northeast2",
      "asia-northeast3",
      "asia-south1",
      "asia-south2",
      "asia-southeast1",
      "asia-southeast2",
      "australia-southeast1",
      "australia-southeast2",
      "europe-central2",
      "europe-north1",
      "europe-southwest1",
      "europe-west1",
      "europe-west10",
      "europe-west12",
      "europe-west2",
      "europe-west3",
      "europe-west4",
      "europe-west6",
      "europe-west8",
      "europe-west9",
      "me-central1",
      "me-central2",
      "me-west1",
      "northamerica-northeast1",
      "northamerica-northeast2",
      "southamerica-east1",
      "southamerica-west1",
      "us-central1",
      "us-east1",
      "us-east4",
      "us-east5",
      "us-south1",
      "us-west1",
      "us-west2",
      "us-west3",
      "us-west4",
    ], var.region)
    error_message = "Invalid Region specified!"
  }
}

variable "create_ssh_key_pair" {
  type        = bool
  description = "Specify if a new SSH key pair needs to be created for the instances"
  default     = true
}

variable "ssh_private_key_path" {
  type        = string
  description = "The full path where is present the pre-generated SSH PRIVATE key (not generated by Terraform)"
  default     = null
}

variable "ssh_public_key_path" {
  description = "The full path where is present the pre-generated SSH PUBLIC key (not generated by Terraform)"
  default     = null
}

variable "ip_cidr_range" {
  type        = string
  default     = "10.10.0.0/24"
  description = "Range of private IPs available for the Google Subnet"
}

variable "vpc" {
  description = "Google VPC used for all resources"
  default     = null
}

variable "subnet" {
  description = "Google Subnet used for all resources"
  default     = null
}

variable "create_firewall" {
  description = "Google Firewall used for all resources"
  default     = true
}

variable "instance_count" {
  default     = 3
  description = "The number of nodes"
}

variable "instance_disk_size" {
  default     = 50
  description = "Size of the disk attached to each node, specified in GB"
}

variable "disk_type" {
  default     = "pd-balanced"
  description = "Type of the disk attached to each node (e.g. 'pd-standard', 'pd-ssd' or 'pd-balanced')"
}

variable "instance_type" {
  default     = "n2-standard-2"
  description = "The name of a Google Compute Engine machine type"
}

variable "os_image" {
  default     = "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230908"
  description = "Ubuntu 22.04 LTS - x86/64, amd64 jammy image built on 2023-09-08"
}

variable "ssh_username" {
  default     = "ubuntu"
  description = "Username used for SSH login"
}

variable "startup_script" {
  default     = null
  description = "Custom startup script"
}
